export type ProjectStatus =
  | "new" | "booting" | "generating" | "installing" | "starting"
  | "checking" | "live" | "error";

export type FrameworkId = "vite-react" | "static" | "next";

export interface FileEntry { path: string; content: string; }

export interface AgentStep {
  id: string;
  kind: "plan" | "write" | "install" | "start" | "check" | "fix" | "done" | "error" | "log" | "db" | "brief" | "verify";
  label: string;
  detail?: string;
  ts: number;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  text: string;
  ts: number;
}

// A restorable point in the project's history — the full source snapshot after a
// successful build. Time-travel is "write these files back + restart", so it works
// even after the underlying microVM has been reaped and re-booted.
export interface Checkpoint {
  id: string;
  label: string;      // e.g. "v3"
  message: string;    // what this build did (codegen summary)
  prompt: string;     // the user prompt that produced it
  files: FileEntry[]; // full app-source snapshot at this point
  createdAt: number;
}

// --- The Brief: what Riff understood, before it builds -----------------------
// Generated by a FAST model in ~1-2s and shown to the user before the first build
// step. It is three things at once: the plan handed to the codegen model, the
// checklist verification runs at the end, and the record of what was decided.

// An assumption Riff made because the prompt didn't say. Shown as a flippable
// chip; flipping one queues a follow-up turn with `alternative` as the directive.
export interface BriefAssumption {
  id: string;
  text: string;         // what we assumed, e.g. "25/5/15 minute defaults"
  alternative: string;  // the other way, e.g. "let the user configure the lengths"
  confidence: number;   // 0..1 — how sure the model is this is what the user meant
  impact: "low" | "med" | "high";
}

// A genuine fork in the road: two or three readings of the same prompt that
// produce structurally different apps. These are what we OFFER TO FORK rather
// than ask about — each reading's `directive` is a ready-made branch directive.
export interface BriefAmbiguity {
  id: string;
  axis: string;         // what differs, e.g. "who the app is for"
  question: string;     // how we'd ask it, if we had to
  readings: { label: string; directive: string }[]; // 2-3, [0] is the one we build
  impact: "low" | "med" | "high";
}

// A single scripted step, for an acceptance item that can only be judged after
// someone has actually used the app. Deliberately tiny: a click, some typing, a
// pause. Anything richer belongs in a test suite, not a build check.
export interface AcceptanceAction {
  kind: "click" | "type" | "wait";
  target: string; // visible label, placeholder or role name — never a CSS selector
  value: string;  // text to type, or milliseconds to wait
}

// One testable claim about the finished app. This is the verify checklist.
export interface AcceptanceItem {
  id: string;
  text: string;                              // "shows the remaining time as mm:ss"
  check: "visual" | "dom" | "interaction";   // how it would be verified
  actions?: AcceptanceAction[];              // only for "interaction" — 1-3 steps
}

export type VerdictStatus = "pass" | "fail" | "unverifiable";
export interface AcceptanceVerdict {
  id: string;            // matches AcceptanceItem.id
  status: VerdictStatus;
  reason: string;        // one line, shown under the item
  fix?: string;          // concrete instruction fed back to codegen on a fail
}

export interface Brief {
  title: string;
  oneLiner: string;
  audience: string;
  jobs: string[];                      // what the user will actually do with it
  screens: { name: string; purpose: string }[];
  entities?: { name: string; fields: string[] }[]; // only when data is implied
  assumptions: BriefAssumption[];
  ambiguities: BriefAmbiguity[];
  acceptance: AcceptanceItem[];
  nonGoals: string[];
  styleDirection: string;
  // Resolved forks — from a user answering the one question, or from keeping a
  // branch. Never re-asked once recorded. The directive is copied inline so a
  // decision keeps working after the Brief is regenerated on a later turn (which
  // mints fresh ambiguity ids).
  decisions: { ambiguityId: string; readingLabel: string; directive?: string; source: "user" | "kept-branch" }[];
  verdicts?: AcceptanceVerdict[];      // last verification pass
  confidence: number;                  // 0..1 overall
  createdAt: number;
  updatedAt: number;
}

// --- taste: what Riff has learned about how this user likes things ------------
// Collected from decisions they already make — which fork they keep, which
// assumption they flip, what they ask for again and again — so it costs them
// nothing to teach and no other builder has the same signal to learn from.
export interface TasteSignal {
  kind: "kept-branch" | "rejected-branch" | "flip" | "correction";
  text: string;
  ts: number;
}
export interface Prefs {
  note: string;            // the distilled sentence or two, injected into prompts
  signals: TasteSignal[];  // raw evidence, capped
  distilledAt: number;     // signal count at the last distillation
  updatedAt: number;
}

export interface DatabaseInfo {
  id: string;                 // pandastack database id
  status: string;             // provisioning | running | error
  connectionUrl?: string;     // postgres://… (injected into the app as DATABASE_URL)
  createdAt: number;
}

// --- Fork-to-explore (P3): branch a running app + its DB into N live variants ---

export type BranchStatus =
  | "spawning" | "cloning-db" | "generating" | "starting" | "checking"
  | "live" | "error" | "kept" | "discarded";

// One live variant: a CoW-forked child sandbox running a divergent codegen.
export interface Branch {
  id: string;                 // "b"+ts+"_"+i
  roundId: string;
  label: string;              // "A" | "B" | "C" | "D"
  directive: string;          // the divergent per-branch prompt (shown on the card)
  parentSandboxId: string;    // trunk (or a parent branch) sandbox that was forked
  sandboxId: string | null;   // forked child (null until forkSandbox returns)
  snapshotId?: string;        // fork provenance
  databaseId?: string | null; // cloned DB id (full-stack only)
  databaseUrl?: string | null;// clone connection_url injected as DATABASE_URL
  status: BranchStatus;
  previewUrl: string | null;
  summary?: string;
  error?: string;
  files: FileEntry[];         // divergent app-source (powers keep-merge + future diff)
  // Set when the round was started to resolve a Brief ambiguity: keeping this
  // branch records the decision on the Brief so it is never re-asked.
  ambiguityId?: string;
  readingLabel?: string;      // human name of the reading, e.g. "customer-facing menu"
  createdAt: number;
}

// A fan-out round: one base prompt → N branches forked off the trunk at a point in time.
export interface BranchRound {
  id: string;                 // "r"+ts
  basePrompt: string;
  fromSandboxId: string;      // trunk sandbox forked (for teardown on keep)
  fromDatabaseId?: string | null;
  baselineFiles: FileEntry[]; // appSrcFiles at fork time — keep-merge base + diff baseline
  baseCheckpointId?: string;
  branchIds: string[];
  keptBranchId?: string;
  // Fork-to-resolve rounds carry the ambiguity they explore, and the reading the
  // TRUNK already represents (so the trunk tile can be kept like any other).
  ambiguityId?: string;
  trunkReadingLabel?: string;
  createdAt: number;
}

export interface Project {
  id: string;                 // riff project id
  name: string;
  sandboxId: string | null;   // pandastack sandbox id
  // The sandbox the fixed harness has actually been written to. "Was this VM just
  // created" is NOT the same question as "does this VM have a package.json on it":
  // the Brief's blocking question boots a VM and then returns, so the turn that
  // resumes afterwards finds a sandbox that is neither fresh nor scaffolded.
  scaffoldedSandboxId?: string | null;
  status: ProjectStatus;
  previewUrl: string | null;
  port: number;
  framework: FrameworkId;
  files: FileEntry[];
  brief?: Brief | null;       // what Riff understood — the spec of record
  checkpoints: Checkpoint[];
  database?: DatabaseInfo | null;
  messages: ChatMessage[];
  steps: AgentStep[];
  // Fork-to-explore (all optional → old projects load unchanged as single-preview mode).
  branches?: Branch[];           // append-only fork history across rounds
  rounds?: BranchRound[];
  activeRoundId?: string | null; // non-null ⇒ the compare grid is showing, not the single preview
  pendingDbDeletes?: string[];   // old source DBs awaiting deletion (blocked until their clone is independent)
  error?: string;
  createdAt: number;
  updatedAt: number;
}
